version: "3.8"
services:
  icecast:
    image: infiniteproject/icecast
    container_name: "radio_icecast"
    ports:
      - "${ICECAST_PORT:-8000}:8000"
    environment:
      - ICECAST_SOURCE_PASSWORD=admin123
      - ICECAST_ADMIN_PASSWORD=admin123
      - ICECAST_RELAY_PASSWORD=admin=123
      - ICECAST_MAX_SOURCES=50
      - ICECAST_ADMIN_EMAIL=testing@testing.com
      - ICECAST_LOCATION=USA
      - ICECAST_HOSTNAME=dev.marvio.co
    restart: unless-stopped

  liquidsoap:
    image: "savonet/liquidsoap:v2.0.2"
    container_name: "radio_liquidsoap"
    depends_on: [icecast]
    command: "liquidsoap /radio_system.liq"
    volumes:
      - "./music:/music:ro"
      - "./config/radio_system.liq:/radio_system.liq:ro"
    environment:
      - ICECAST_SOURCE_PASSWORD=admin123
      - STREAM_NAME=Station
      - STREAM_DESC=New Station Pro web Radio!
      - STREAM_URL=radio.stationpro.co
      - STREAM_MOUNTPOINT=autodj
    restart: unless-stopped